rmdir /s /q "NumFlat\bin"
rmdir /s /q "NumFlat\obj"
rmdir /s /q "NumFlatTest\bin"
rmdir /s /q "NumFlatTest\obj"
rmdir /s /q "SerializationJson\bin"
rmdir /s /q "SerializationJson\obj"
rmdir /s /q "SerializationJsonTest\bin"
rmdir /s /q "SerializationJsonTest\obj"
rmdir /s /q "Workspace\bin"
rmdir /s /q "Workspace\obj"
rmdir /s /q "TestResults"
pause
